version: '3'

services:
#  db:
#    image: postgres:13
#    environment:
#      POSTGRES_DB: myproject_db
#      POSTGRES_USER: myproject_user
#      POSTGRES_PASSWORD: myproject_password
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - myproject_network

#  redis:
#    image: redis:6
#    networks:
#      - myproject_network

  web:
    build: .
    command: gunicorn first_deploy.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
#    ports:
#      - "8000:8000"
    env_file:
      - .env
#    depends_on:
#      - db
#      - redis
    networks:
      - myproject_network

#  celery:
#    build: .
#    command: celery -A myproject worker --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - db
#      - redis
#    env_file:
#      - .env
#    networks:
#      - myproject_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - myproject_network

#volumes:
#  postgres_data:

networks:
  myproject_network:
    driver: bridge
